CREATE TABLE BIOMAS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    DISTRIBUICAO VARCHAR(200),
    CARACTERISTICAS VARCHAR(65535), 
    FITOFISIONOMIA VARCHAR(65535),
    OBSERVACAO VARCHAR(65535),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE IMAGENSBIOMA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDBIOMA INT NOT NULL,
    CAMINHO VARCHAR(300),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDBIOMA) REFERENCES BIOMAS(ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE PLANTAS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDBIOMA INT NOT NULL,
    NOMECIENTIFICO VARCHAR(200),
    NOMEPOPULAR VARCHAR(200),
    HABITATE VARCHAR(1000),
    FOLHA VARCHAR(1000),
    FLOR VARCHAR(1000),
    FRUTO VARCHAR(1000),
    FAMILIA VARCHAR(200),
    TRIBO VARCHAR(200),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDBIOMA) REFERENCES BIOMAS(ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE IMAGENSPLANTA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDPLANTA INT NOT NULL,
    CAMINHO VARCHAR(300),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDPLANTA) REFERENCES PLANTAS(ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE USUARIOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    PASS VARCHAR(12) NOT NULL,
    NOME VARCHAR(50) NOT NULL
);

INSERT INTO USUARIOS (LOGIN, PASS, NOME) VALUES ('milena', '12345', 'Milena Arantes Bertolini');
INSERT INTO USUARIOS (LOGIN, PASS, NOME) VALUES ('rodrigo', '12345', 'Rodrigo Borges Machado');