
CREATE TABLE BIOMAS(
    ID INT PRIMARY KEY,
    NOME VARCHAR(200),
    DISTRIBUICAO VARCHAR(200),
    CARACTERISTICAS VARCHAR(8000), 
    FITOFISIONOMIA VARCHAR(8000),
    OBSERVACAO VARCHAR(8000),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE IMAGENSBIOMA(
    ID INT PRIMARY KEY,
    IDBIOMA INT NOT NULL,
    CAMINHO VARCHAR(300),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDBIOMA) REFERENCES BIOMAS(ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE PLANTAS(
    ID INT PRIMARY KEY,
    IDBIOMA INT NOT NULL,
    NOMECIENTIFICO VARCHAR(200),
    NOMEPOPULAR VARCHAR(200),
    HABITATE VARCHAR(1000),
    FOLHA VARCHAR(8000),
    FLOR VARCHAR(8000),
    FRUTO VARCHAR(8000),
    FAMILIA VARCHAR(200),
    TRIBO VARCHAR(200),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDBIOMA) REFERENCES BIOMAS(ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);

CREATE TABLE IMAGENSPLANTA(
    ID INT PRIMARY KEY,
    IDPLANTA INT NOT NULL,
    CAMINHO VARCHAR(300),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDPLANTA) REFERENCES PLANTAS(ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(ID) 
);


CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    PASS VARCHAR(12) NOT NULL,
    NOME VARCHAR(50) NOT NULL
);



INSERT INTO USUARIOS (id, LOGIN, PASS, NOME) VALUES (0, 'milena', '12345', 'Milena Arantes Bertolini');
INSERT INTO USUARIOS (id, LOGIN, PASS, NOME) VALUES (1, 'rodrigo', '12345', 'Rodrigo Borges Machado');